### PR TITLE
Fix jedi version check

### PR DESCRIPTION
**Pull request by mrparalon**
According to code v 0.18 was requeired

### CODE REVIEW

**Comment by kuznero** [comment]
Is there a workaround for now? Can I `:CocInstall coc-pythong-from-branch`?

**Comment by ikornaselur** [comment]
> Is there a workaround for now? Can I `:CocInstall coc-pythong-from-branch`?

While not optimal, at least for now, I edited the source locally:

```
~/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py:698
```

doing the same change as in this PR, until this is merged and released.

**Comment by kuznero** [comment]
Nice! I can confirm that this PR fixes the problem. Please merge and release!

**Comment by chemzqm** [comment]
You can specifiy version by `CocInstall coc-python@1.2.10`

**Comment by her** [comment]
Thanks for the fast release turnaround @chemzqm 👍

**Comment by codehia** [comment]
I tried this, the error still persists. 

```
[coc.nvim] Jedi error:     raise RuntimeError("Jedi version %s too old, requires >= 0.17.0" % (jedi.__vers
ion__))
RuntimeError: Jedi version 0.16.0 too old, requires >= 0.17.0
```

**Comment by chemzqm** [comment]
Use `:CocList extensions` to check installed extenisons

**Comment by codehia** [comment]
it's
```
coc-prettier 1.1.14
coc-clangd 0.4.10
coc-python 1.2.10
coc-json 1.2.6
```

**Comment by chemzqm** [comment]
It means your jedi need upgrade to work with coc-python.

**Pull request merged**
